apiVersion: v1 # Kubernetes API version for Service
kind: Service # Type of Kubernetes resource
metadata:
  name: vprodb # Name of the Service
spec:
  ports:
  - port: 3306 # Port on which the Service will be exposed
    targetPort: vprodb-port # Port on the Pods to which the Service forwards traffic
    protocol: TCP # Protocol used for the port
  selector:
    app: vprodb # Selects Pods with label 'app: vprodb' to route traffic to
  type: ClusterIP # Type of Service (ClusterIP makes the Service reachable only from within the cluster)

