apiVersion: v1 # Kubernetes API version for Service
kind: Service # Type of Kubernetes resource
metadata:
  name: vpromq01 # Name of the Service
spec:
  ports:
  - port: 5672 # Port on which the Service will be exposed
    targetPort: vpromq01-port # Port on the Pods to which the Service forwards traffic
    protocol: TCP # Protocol used for the port
  selector:
    app: vpromq01 # Selects Pods with label 'app: vpromq01' to route traffic to
  type: ClusterIP # Type of Service (ClusterIP makes the Service reachable only from within the cluster)

