apiVersion: networking.k8s.io/v1 # Kubernetes API version for Ingress
kind: Ingress # Type of Kubernetes resource
metadata:
  name: vpro-ingress # Name of the Ingress resource
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true" # Annotation to enable regex support
spec:
  ingressClassName: nginx # Class name of the Ingress controller
  rules:
  - host: thiti-kubevpro.thitidevops.store # Hostname for routing
    http:
      paths:
      - path: / # Path to match
        pathType: Prefix # Type of path matching
        backend:
          service:
            name: my-app # Name of the backend service
            port:
              number: 8080 # Port 
