apiVersion: v1 # Kubernetes API version for Service
kind: Service # Type of Kubernetes resource
metadata:
  name: vprocache01 # Name of the Service
spec:
  ports:
  - port: 11211 # Port on which the Service will be exposed
    targetPort: vpromc-port # Port on the Pods to which the Service forwards traffic
    protocol: TCP # Protocol used for the port
  selector:
    app: vpromc # Selects Pods with label 'app: vpromc' to route traffic to
  type: ClusterIP # Type of Service (ClusterIP makes the Service reachable only from within the cluster)

