apiVersion: v1 # Kubernetes API version for Service
kind: Service # Type of Kubernetes resource
metadata:
  name: my-app # Name of the Service
spec:
  ports:
  - port: 8080 # Port on which the Service will be exposed
    protocol: TCP # Protocol used for the port
    targetPort: 8080 # Port on the Pods to which the Service forwards traffic
  selector:
    app: vproapp # Selects Pods with label 'app: vproapp' to route traffic to
  type: ClusterIP # Type of Service (ClusterIP makes the Service reachable only from within the cluster)

